name: Deploy Node.js API to VPS

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install --legacy-peer-deps

            - name: Build TypeScript
              run: npm run build

            - name: Prepare deployment on server
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      sudo rm -rf /var/www/one-daily-blog-backend/*
                      sudo mkdir -p /var/www/one-daily-blog-backend
                      sudo chown -R ${{ secrets.VPS_USER }}:$USER /var/www/one-daily-blog-backend
                      sudo chmod -R 775 /var/www/one-daily-blog-backend

            - name: Deploy files via SSH
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  source: "dist/*"
                  target: "/var/www/one-daily-blog-backend"

            - name: Start Node.js API
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      pm2 reload all --update-env || pm2 start /var/www/one-daily-blog-backend/dist/server.js --name "one-daily-blog-backend" --watch
